# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20170109_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='slug',
        ),
    ]
