# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_auto_20170115_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='imgFile',
            field=models.FileField(default='P', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
