# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_docno_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docno',
            name='currNo',
            field=models.IntegerField(default=0),
        ),
    ]
