# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_auto_20170116_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='docno',
            name='format',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
