# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0011_auto_20170116_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='retail.Customer'),
            preserve_default=False,
        ),
    ]
