# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0012_price_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_det',
            name='net_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
