# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0017_auto_20170212_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
