# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0018_auto_20170212_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='doc_net_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
