# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0021_auto_20170217_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIM_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='dim_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.DIM_Type'),
        ),
    ]
