# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0022_auto_20170219_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DIM_Type',
            new_name='DIM_Category',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='dim_type',
            new_name='dim_category',
        ),
    ]
