# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0023_auto_20170219_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('pageTitle', models.CharField(max_length=200)),
                ('pageSectionHeader', models.CharField(max_length=50)),
                ('pageSectionArticle', models.CharField(max_length=200)),
                ('pageSectionimgFile', models.FileField(upload_to='documents/Template/')),
                ('pageURL', models.URLField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
