# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0026_dim_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='dim_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.DIM_SubCategory'),
        ),
    ]
