# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0028_auto_20170321_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='dim_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.DIM_Category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='dim_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.DIM_SubCategory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='dim_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.DIM_Unit'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='imgFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
